### ISSUE TITLE
Could not open model_kmer.csv

### ISSUE THREAD

**Issue by liu2005678** [comprna/CHEUI#10]
**Hi, i used the follow command:
 python3 ../scripts/CHEUI_predict_model2.py -i /media/logen/sd16b/Hp/cheui/nanopolish_out_26695.txt -m ../kmer_models/model_kmer.csv -o out_A_signals+IDs.p -n 15

it reports wrong:** 

2022-12-05 18:18:02.188272: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-12-05 18:18:03.597052: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-12-05 18:18:03.598138: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
2022-12-05 18:18:03.639249: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:04:00.0 name: NVIDIA GeForce GTX 1080 computeCapability: 6.1
coreClock: 1.7845GHz coreCount: 20 deviceMemorySize: 7.92GiB deviceMemoryBandwidth: 298.32GiB/s
2022-12-05 18:18:03.639297: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-12-05 18:18:03.641257: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2022-12-05 18:18:03.641297: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2022-12-05 18:18:03.642909: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2022-12-05 18:18:03.643223: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2022-12-05 18:18:03.645643: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2022-12-05 18:18:03.646885: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2022-12-05 18:18:03.651311: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2022-12-05 18:18:03.651775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2022-12-05 18:18:03.652146: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-05 18:18:03.653928: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
2022-12-05 18:18:03.654179: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:04:00.0 name: NVIDIA GeForce GTX 1080 computeCapability: 6.1
coreClock: 1.7845GHz coreCount: 20 deviceMemorySize: 7.92GiB deviceMemoryBandwidth: 298.32GiB/s
2022-12-05 18:18:03.654208: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-12-05 18:18:03.654237: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublas.so.10
2022-12-05 18:18:03.654262: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcublasLt.so.10
2022-12-05 18:18:03.654287: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcufft.so.10
2022-12-05 18:18:03.654311: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcurand.so.10
2022-12-05 18:18:03.654362: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusolver.so.10
2022-12-05 18:18:03.654402: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcusparse.so.10
2022-12-05 18:18:03.654428: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudnn.so.7
2022-12-05 18:18:03.654756: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2022-12-05 18:18:03.654798: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
2022-12-05 18:18:04.339973: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2022-12-05 18:18:04.340033: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2022-12-05 18:18:04.340045: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2022-12-05 18:18:04.340764: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 7130 MB memory) -> physical GPU (device: 0, name: NVIDIA GeForce GTX 1080, pci bus id: 0000:04:00.0, compute capability: 6.1)
2022-12-05 18:18:04.993160: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open ../kmer_models/model_kmer.csv: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "../scripts/CHEUI_predict_model2.py", line 114, in <module>
    model.load_weights(secondML_path)
  File "/home/logen/anaconda3/envs/cheui/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2227, in load_weights
    with h5py.File(filepath, 'r') as f:
  File "/home/logen/anaconda3/envs/cheui/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/home/logen/anaconda3/envs/cheui/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

**It shouldn't be the problem of model_kmer.csv. since I could open it. 
And the test sentence works:
python3 ../scripts/CHEUI_preprocess_m6A.py -i nanopolish_output_test.txt -m ../kmer_models/model_kmer.csv -o out_A_signals+IDs.p -n 15**

**the first ten row of  nanopolish_out_26695.txt  is:**

contig	position	reference_kmer	read_name	strand	event_index	event_level_mean	event_stdv	event_length	model_kmer	model_mean	model_stdv	standardized_level	start_idx	end_idx	samples
lcl|NC_018939.1_cds_WP_001165637.1_2	299	TATTG	166588ca-0972-47be-b76d-9a9124773666	t	1	92.61	2.517	0.00830	TATTG	94.79	5.53	-0.34	23504	23529	91.0363,91.3671,88.7207,93.0212,96.4946,90.0439,92.525,90.2093,94.0136,92.6904,97.3216,92.8558,93.0212,94.5098,99.4719,87.5629,95.1714,88.0591,93.8482,91.3671,89.5477,95.006,94.3444,92.1942,90.8709
lcl|NC_018939.1_cds_WP_001165637.1_2	300	ATTGC	166588ca-0972-47be-b76d-9a9124773666	t	2	85.50	1.788	0.00199	ATTGC	83.88	2.65	0.53	23498	23504	85.9088,86.9013,85.0818,86.7358,87.0667,81.2775
lcl|NC_018939.1_cds_WP_001165637.1_2	301	TTGCC	166588ca-0972-47be-b76d-9a9124773666	t	3	90.04	2.549	0.00332	TTGCC	89.55	3.13	0.14	23488	23498	89.5477,92.525,86.405,84.5856,92.1942,89.7131,95.006,91.5325,89.3823,89.5477
lcl|NC_018939.1_cds_WP_001165637.1_2	301	TTGCC	166588ca-0972-47be-b76d-9a9124773666	t	4	87.49	2.808	0.00564	TTGCC	89.55	3.13	-0.58	23471	23488	92.0287,90.5401,86.9013,84.5856,86.0742,86.9013,88.3899,94.0136,89.2169,88.5553,83.924,89.8785,80.9467,85.578,89.3823,84.5856,85.7434
lcl|NC_018939.1_cds_WP_001165637.1_2	301	TTGCC	166588ca-0972-47be-b76d-9a9124773666	t	5	93.08	2.956	0.00498	TTGCC	89.55	3.13	0.99	23456	23471	91.6979,94.3444,93.0212,93.6828,99.3065,90.7055,97.3216,87.5629,93.8482,92.1942,88.7207,92.3596,90.8709,99.3065,91.2017
lcl|NC_018939.1_cds_WP_001165637.1_2	301	TTGCC	166588ca-0972-47be-b76d-9a9124773666	t	6	87.81	1.698	0.00332	TTGCC	89.55	3.13	-0.49	23446	23456	87.7283,90.3747,86.0742,89.8785,87.0667,87.3975,83.7586,88.2245,90.0439,87.5629
lcl|NC_018939.1_cds_WP_001165637.1_2	301	TTGCC	166588ca-0972-47be-b76d-9a9124773666	t	7	90.20	2.765	0.00896	TTGCC	89.55	3.13	0.18	23419	23446	87.0667,87.8937,91.5325,88.7207,85.0818,90.2093,83.924,88.7207,86.7358,91.6979,88.3899,90.3747,93.8482,90.0439,95.5022,87.0667,88.2245,95.5022,92.0287,87.8937,92.8558,95.006,90.2093,95.1714,89.2169,89.7131,92.8558
lcl|NC_018939.1_cds_WP_001165637.1_2	301	TTGCC	166588ca-0972-47be-b76d-9a9124773666	t	8	84.27	1.651	0.00764	TTGCC	89.55	3.13	-1.48	23396	23419	84.0894,83.7586,90.0439,84.5856,85.2472,84.751,84.751,84.4202,80.2851,81.2775,82.27,85.7434,83.4278,85.7434,85.578,84.4202,84.0894,82.9316,84.0894,86.0742,84.0894,83.924,82.6008
lcl|NC_018939.1_cds_WP_001165637.1_2	301	TTGCC	166588ca-0972-47be-b76d-9a9124773666	t	9	81.79	1.298	0.00896	TTGCC	89.55	3.13	-2.17	23369	23396	82.7662,81.7738,80.2851,81.4429,83.924,83.924,79.9543,80.9467,83.5932,79.4581,84.2548,82.4354,79.9543,82.27,81.4429,80.6159,82.4354,78.7965,81.9392,81.9392,82.9316,81.2775,80.4505,84.0894,80.7813,81.7738,82.9316

**Comment by liu2005678** [comment]
Solved, sorry. It's the error of commands. I missed the preprocessing step!
